spring.application.name=cote-noire-backend

server.port=8086

spring.datasource.url=jdbc:mysql://localhost:3306/coteNoireBackend?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true




